version: '3.9'

networks:
  traefik:
    name: traefik

services:
  code:
    build:
      context: code
      x-bake:
        output: type=docker,dest=./${COMPOSE_PROJECT_NAME}-code.tar.gz
    image: ${COMPOSE_PROJECT_NAME}-code:latest
    user: 1000:1000
    environment:
      - DOCKER_USER=ubuntu
    volumes:
      - ./code/config:/home/coder/.config/code-server
      - ./code/share/user/settings.json:/home/coder/.local/share/code-server/User/settings.json
      - ./code/share/coder.json:/home/coder/.local/share/code-server/coder.json
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-code.rule=Host(`code-${DOMAIN:-${COMPOSE_PROJECT_NAME}.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-code.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-code.service=${COMPOSE_PROJECT_NAME}-code
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-code.loadbalancer.server.port=8080
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-preview.rule=Host(`preview-${DOMAIN:-${COMPOSE_PROJECT_NAME}.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-preview.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-preview.service=${COMPOSE_PROJECT_NAME}-preview
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-preview.loadbalancer.server.port=5173

  app:
    depends_on:
      - code
    build:
      x-bake:
        output: type=docker,dest=./${COMPOSE_PROJECT_NAME}-app.tar.gz
    image: ${COMPOSE_PROJECT_NAME}-app:latest
    volumes:
      - ./public:/app/public
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DOMAIN:-${COMPOSE_PROJECT_NAME}.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=web
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=4173
